#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/capture/javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domain:
  english: "http://www.live.bbc.co.uk/news"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  # - 768
  - 1024
  # - 1280

#Type page URL paths below, here are a couple of examples
paths:
  home: /
  uk_index: /uk
